CREATE DATABASE [FacturadorDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FacturadorDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FacturadorDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FacturadorDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FacturadorDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [FacturadorDB] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [FacturadorDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FacturadorDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FacturadorDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FacturadorDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FacturadorDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FacturadorDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FacturadorDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FacturadorDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [FacturadorDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FacturadorDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FacturadorDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FacturadorDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FacturadorDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FacturadorDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FacturadorDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FacturadorDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FacturadorDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FacturadorDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FacturadorDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FacturadorDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FacturadorDB] SET  READ_WRITE 
GO
ALTER DATABASE [FacturadorDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FacturadorDB] SET  MULTI_USER 
GO
ALTER DATABASE [FacturadorDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FacturadorDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FacturadorDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [FacturadorDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [FacturadorDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [FacturadorDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
